### ISSUE TITLE
Failed to play video

### ISSUE THREAD

**Issue by manowar222** [alvarorichard/GoAnime#30]
It downloads the episode, but fails to play it.
![Screenshot from 2024-03-03 02-02-24](https://github.com/alvarorichard/GoAnime/assets/82991765/e520a606-3216-4661-bbab-e53714bd0760)

**Comment by alvarorichard** [comment]
How did you install it, perhaps it is not able to access the location where it is downloaded?

You can also test just by running the code by executing it with the go run `main.go` command

**Comment by manowar222** [comment]
Updating VLC solved it.

Weird - I installed it just for testing your project, I imagined it would be the latest.

Anyway, thanks.
