### ISSUE TITLE
Failed to extract video URL: failed to fetch video source: Get "": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by lostdusty** [alvarorichard/GoAnime#34]
Pesquisando por `princess principal`, selecionando a primeira opção e o primeiro episódio retorna isso.

![image](https://github.com/alvarorichard/GoAnime/assets/47502554/e57450fa-494e-4a93-9ea5-56c3369859ac)

**Comment by alvarorichard** [comment]
I apologize for this, but some animes are accessed via API. The majority of animes work without any issues, but some don't work because the API is not yet functional with GoAnime.
